<h1 class="title"><span>(E3) </span>Countries:&nbsp;Similar</h1>
<div>In this question you are required to&nbsp; <span><strong>write </strong></span><span><strong>code</strong></span>, implementing a solution to the problem described below.</div>
<p><span>Use the dataset from the previous question (<strong>the correct result of E1</strong>),</span>&nbsp;uploaded into the working directory.&nbsp;</p>
<div>
  <p>In this question, you are asked to implement a similarity function which can ﬁnd the most similar country to a new country given its scores for the diﬀerent categories.</p>
  <p>Create a function where given a new country and its scores for <code>GDP</code>, <code>Social_support</code>, <code>Life_expectancy</code>, <code>Freedom</code>, <code>Generosity</code>, <code>Corruption</code>, you will return the country that is most similar to the target based on the scores for <code>Year = 2019</code>. All features have equal weight, and overall similarity is measured by euclidean distance.</p>
</div>
<h2>Input format</h2>
<div class="input-specification">
  <p>One row containing country name and values for &nbsp;<code>GDP</code>, <code>Social_support</code>, <code>Life_expectancy</code>, <code>Freedom</code>, <code>Generosity</code>, <code>Corruption</code>. Values are listed are in this order, separated with comma.</p>
</div>
<div class="input-specification"><span><span><span style="font-weight: bold;">Data</span>:<br><span style="font-family: monospace;">countries.csv</span> (</span></span>A pre-processed ﬁle as result of E1 which served as the data for this task<span>).</span></div>
<h2>Output format</h2>
<div class="output-specification">
  <p>Print one text value – the name of the country most similar to target for the year <strong>2019</strong>.</p>
  <h3>Sample 1</h3>
  <table class="sample-tests" style="height: 79px; border-collapse: collapse;" width="496">
    <thead>
      <tr>
        <th style="border: 2px solid #fff;">Input</th>
        <th style="border: 2px solid #fff;">Output</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="border: 2px solid #fff; text-align: center;">
          <pre class="content">'Imagination Land', 0.88, 1.2, 0.89, 0.62, 0.3, 0.5</pre>
        </td>
        <td style="border: 2px solid #fff; text-align: center;">
          <pre>Uzbekistan</pre>
        </td>
      </tr>
    </tbody>
  </table>
  <h3>Sample 2</h3>
  <table class="sample-tests" style="height: 79px; border-collapse: collapse;" width="485">
    <thead>
      <tr>
        <th style="border: 2px solid #fff;">Input</th>
        <th style="border: 2px solid #fff;">Output</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="border: 2px solid #fff; text-align: center;">
          <pre class="content">'OverTheRainbow', 0.45, 0.99, 0.56, 0.09, 0.5, 0.233</pre>
        </td>
        <td style="border: 2px solid #fff; text-align: center;">
          <pre>Haiti</pre>
        </td>
      </tr>
    </tbody>
  </table>
  <div>
    <h3>Sample 3</h3>
    <table class="sample-tests" style="height: 85px; border-collapse: collapse;" width="496">
      <thead>
        <tr>
          <th style="border: 2px solid #fff;">Input</th>
          <th style="border: 2px solid #fff;">Output</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="border: 2px solid #fff; text-align: center;">
            <pre class="content">'Fantasia', 0.95, 1.30, 1.2, 1.09, 0.4, 0.333</pre>
          </td>
          <td style="border: 2px solid #fff; text-align: center;">
            <pre>New Zealand</pre>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<h2>Notes</h2>
<div class="notes">Maximum points for question E3:<strong> 13</strong>&nbsp;points.<!--l. 80--></div>
<div class="notes">&nbsp;</div>
<div class="notes">
  <p style="text-indent: 0em;"><span style="font-weight: bold;">Reminder: </span>You must select 2 out of 3 questions in programming section: Sums (D), Countries (E), Streaming (F), and answer both selected questions as fully as possible (for example, if you choose Sums and Streaming, you should answer questions D1, D2, D3 and F1, F2, F3).</p>
</div>

In [ ]:
### Initial candidate answer code

In [ ]:
# Use print("Debug messages...") to debug your solution.

def solution(countries, query):
    # Your code goes here
    return 0

In [ ]:
### Initial candidate test code

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime

countries = pd.read_csv('./datasets/E3/countries.csv', sep=",")
print(countries.head())

query1 = ['Imagination Land', 0.88, 1.2, 0.89, 0.62, 0.3, 0.5]    
print(query1)
print(solution(countries, query1), '\n')

query2 = ['OverTheRainbow', 0.45, 0.99, 0.56, 0.09, 0.5, 0.233]    
print(query2)
print(solution(countries, query2), '\n') 

query3 = ['Fantasia', 0.95, 1.30, 1.2, 1.09, 0.4, 0.333]    
print(query3)
print(solution(countries, query3), '\n')